package edu.wesimulated.firstapp.simulation.stochastic;

public enum StochasticVar {
	BUGS_X_UOW,
	DURATION_WORK_SLAB,
	NEXT_WORK_TYPE_FOR_ROLE,
	REWORK_X_REVIEW_TIME,
	REWORK_X_QC_TIME,
	REWORK_X_AUTO_QC,
	EFFECTIVE_UOW_X_TIME_WORKED,
	TIME_TO_FOCUS,
	MESSAGE_STATUS,
	TIME_TO_RESOLVE_IM,
	TIME_TO_READ_EMAIL,
	TIME_TO_RESPOND_EMAIL,
	EMAILS_NEEDS_RESPONSE,
	TIME_TO_LISTEN_FACE_TO_FACE_INTERACTION,
	TIME_TO_RESPOND_FACE_TO_FACE_INTERACTION,
	SQUEALER_REQUEST_STATUS,
	TIME_TO_RESOLVE_SQUEALER_REPORT,
	TIME_TO_ISSUE_SQUEALER_REPORT, 
	MEETING_DURATION, 
	PERIOD_OF_ERRORS
}
